#!/bin/bash
NC='\e[0m'
# Valid Script
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/QueenGoo/v7/main/ipmini"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          IZIN KE OWNER DULU ASU       \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/Alvi_cell"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6282183496832"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
clear
Repo1="https://raw.githubusercontent.com/QueenGoo/v7/main/"
export MYIP=$( curl -s https://ipinfo.io/ip/ )
SELLER=$(curl -sS ${Repo1}ip | grep $MYIP | awk '{print $2}')
Exp100=$(curl -sS ${Repo1}ip | grep $MYIP | awk '{print $3}')
data_ip="https://raw.githubusercontent.com/QueenGoo/v7/main/ipmini"
d2=$(date -d "$date_list" +"+%s")
d1=$(date -d "$Exp" +"+%s")
dayleft=$(( ($d1 - $d2) / 86400 ))

#########################
[[ ! -f /usr/bin/git ]] && apt install git -y &> /dev/null
# COLOR VALIDATION
clear
OR='\033[1;93m'
c="\033[0;36m" #biruterang
g="\e[92;1m"
r="\033[1;31m"  #REDTERANG
NC='\e[0m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
grenbo="\033[1;95m"
yell='\e[33m'
BGX="\033[42m"
END='\e[0m'
AKTIF="online"
TOKEN="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"
REPO="https://github.com/QueenGoo/v7.git"
EMAIL="muhfaruq2024@gmail.com"
USER="QueenGoo"


add-ip() {
TIMES="10"
CHATID="6993894531"
KEY="6302933990:AAHbwBHappL3_TUdbmUKqsbJdutaCRsMMPs"
URL="https://api.telegram.org/bot$KEY/sendMessage"


    today=`date -d "0 days" +"%Y-%m-%d"`
    git clone ${REPO} /root/v7/ &> /dev/null
    clear
    echo -e "MASUKAN IP VPS YANG BELUM DI DAFTAR !"
    echo -e ""
    read -p "Input IP Address : " ip
    CLIENT_EXISTS=$(grep -w $ip /root/v7/main/ipmini | wc -l)
    if [[ ${CLIENT_EXISTS} == '1' ]]; then
    echo "IP Already Exist !"
    exit 0
    fi
    echo -e ""
   # read -p "  Input Username IP (Example : Alvi) : " name
    name=H6EFctYeZ3DqOWSai`</dev/urandom tr -dc A-Z0-9 | head -c4`
    echo -e ""
    clear
    echo -e " ${r} How Much Days Do You Want ?${NC}"
    echo -e "  ${OR} 1.${NC}${c} 30 Days${NC}"
    echo -e "  ${OR} 2.${NC}${c} 60 Days${NC}"
    echo -e "  ${OR} 3.${NC}${c} 90 Days${NC}"
    echo -e "  ${OR} 4.${NC}${c} Lifetime${NC}"
    echo -e "  ${OR} 5.${NC}${c} Custom Expiration Date${NC}"
    echo -e ""
    read -p "Select Number 1 - 5 : " exp
    
    if [[ ${exp} == '1' ]]; then
    exp2=`date -d "30 days" +"%Y-%m-%d"`
    echo "### ${name} ${exp2} ${ip}" >> /root/v7/main/ipmini
    elif [[ ${exp} == '2' ]]; then
    exp2=`date -d "60 days" +"%Y-%m-%d"`
    echo "### ${name} ${exp2} ${ip}" >> /root/v7/main/ipmini
    elif [[ ${exp} == '3' ]]; then
    exp2=`date -d "90 days" +"%Y-%m-%d"`
    echo "### ${name} ${exp2} ${ip}" >> /root/v7/main/ipmini
    elif [[ ${exp} == '4' ]]; then
    exp2=`date -d "360 days" +"%Y-%m-%d"`
    echo "### ${name} ${exp2} ${ip}" >> /root/v7/main/ipmini
    elif [[ ${exp} == '5' ]]; then
    read -p "Input Expired Days : " exp11
    exp2=`date -d "$exp11 days" +"%Y-%m-%d"`
    echo "### ${name} ${exp2} ${ip}" >> /root/v7/main/ipmini
    fi
    cd /root/permission
    git config --global user.email "${EMAIL}" &> /dev/null
    git config --global user.name "${USER}" &> /dev/null
    rm -rf .git &> /dev/null
    git init &> /dev/null
    git add . &> /dev/null
    git commit -m m &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/QueenGoo/v7
    git push -f https://${TOKEN}@github.com/QueenGoo/v7.git &> /dev/null
    rm -rf /root/v7
    clear
    sleep 1
    echo "  Registering IP Address..."
    sleep 1
    echo "  Processing..."
    sleep 1
    echo "  Done!"
    sleep 1
    clear
TEXT="
<code>───────────────────────────</code>
<code>    SUCCES  REGISTERED IP VPS</code>
<code>───────────────────────────</code>
<code>USERNAME       : $name</code>
<code>IP Address     : $ip</code>
<code>Registered On  : $today</code>
<code>Expired On     : $exp2</code>
<code>───────────────────────────</code>
"
    echo -e "${OR}┌───────────────────────────────┐$NC"
    echo -e "${OR}│${NC}${g} .::.${NC} SUCCES ADD IP VPS ${NC}${g}.::. $NC"
    echo -e "${OR}└───────────────────────────────┘$NC"
    echo -e "${OR}> USERNAME   :${NC}${yell} $name"
    echo -e "${OR}> IP ADDRESS :${NC}${yell} $ip"
    echo -e "${OR}> REGISTERED :${NC}${yell} $today"
    echo -e "${OR}> EXPIRED ON :${NC}${yell} $exp2"
    echo -e " ${OR}────────────────────────────────$NC"
    echo -e ""
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

del-ip() {
TIMES="10"
CHATID="6993894531"
KEY="6302933990:AAHbwBHappL3_TUdbmUKqsbJdutaCRsMMPs"
URL="https://api.telegram.org/bot$KEY/sendMessage"

    rm -rf /root/QueenGoo/v7
    git clone ${REPO} /root/v7/ &> /dev/null
    clear
    echo ""
    echo -e "${OR}┌───────────────────────────────┐$NC"
    echo -e "${OR}│${NC}${g} .::.${NC}    LIST IP VPS     ${NC}${g}.::. $NC"
    echo -e "${OR}└───────────────────────────────┘$NC"
    grep -E "^###" "/root/v7/main/ipmini" | cut -d ' ' -f 2-6 | column -t | sort | uniq
    grep -E "^#&"  "/root/v7/main/ipmini" | cut -d ' ' -f 2-6 | column -t | sort | uniq
    echo -e " ${OR}────────────────────────────────$NC"

    read -p "Input IP Address To Delete : " ipdel
    name=$(cat /root/v7/main/ipmini | grep $ipdel | awk '{print $2}')
    exp=$(cat /root/v7/main/ipmini | grep $ipdel | awk '{print $3}')
    if [[ ${exp} == 'Lifetime' ]]; then
    sed -i "/^#&   $name   $exp $ipdel/,/^},{/d" /root/v7/main/ipmini
    else
    sed -i "/^### $name $exp $ipdel/,/^},{/d" /root/v7/main/ipmini
    fi
    cd /root/v7
    git config --global user.email "${EMAIL}" &> /dev/null
    git config --global user.name "${USER}" &> /dev/null
    rm -rf .git &> /dev/null
    git init &> /dev/null
    git add . &> /dev/null
    git commit -m m &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/QueenGoo/v7
    git push -f https://${TOKEN}@github.com/QueenGoo/v7.git &> /dev/null
    rm -rf /root/v7
    clear
    sleep 1
    echo "  Delete IP Address..."
    sleep 1
    echo "  Processing..."
    sleep 1
    echo "  Done!"
    sleep 1
    clear
TEXT1="
<code>───────────────────────────</code>
<code>    SUCCES DELETE  IP VPS</code>
<code>───────────────────────────</code>
<code>USERNAME       : $name</code>
<code>IP Address     : $ipdel</code>
<code>Expired On     : $exp</code>
<code>───────────────────────────</code>
"
    echo -e "${OR}┌───────────────────────────────┐$NC"
    echo -e "${OR}│${NC}${g} .::.${NC} DONE DELETE IP VPS ${NC}${g}.::. $NC"
    echo -e "${OR}└───────────────────────────────┘$NC"
    echo -e "${OR}> USERNAME   :${NC}${yell} $name"
    echo -e "${OR}> IP ADDRESS :${NC}${yell} $ipdel"
    echo -e "${OR}> EXPIRED ON :${NC}${yell} $exp"
    echo -e " ${OR}────────────────────────────────$NC"
    echo -e ""
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT1&parse_mode=html" $URL >/dev/null
}

renew-ip() {
TIMES="10"
CHATID="6993894531"
KEY="6302933990:AAHbwBHappL3_TUdbmUKqsbJdutaCRsMMPs"
URL="https://api.telegram.org/bot$KEY/sendMessage"

    rm -rf /root/v7
    git clone ${REPO} /root/v7/ &> /dev/null
    clear
    echo -e "${OR}┌───────────────────────────────┐$NC"
    echo -e "${OR}│${NC}${g}  .::.${NC} RENEW IP VPS ${NC}${g}.::. $NC"
    echo -e "${OR}└───────────────────────────────┘$NC"
    grep -E "^###" "/root/v7/main/ipmini" | cut -d ' ' -f 2-6 | column -t | sort | uniq
    echo -e " ${OR}────────────────────────────────$NC"
    echo ""
    read -p "  Input IP Address To Renew : " ipdel
    read -p "  Input Days  : " days
    name=$(cat /root/v7/main/ipmini | grep $ipdel | awk '{print $2}')
    exp=$(cat /root/v7/main/ipmini | grep $ipdel | awk '{print $3}')
    now=$(date +%Y-%m-%d)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    exp3=$(($exp2 + $days))
    exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
    sed -i "s/### $name $exp $ipdel/### $name $exp4 $ipdel/g" /root/v7/main/ipmini
    cd /root/v7
    git config --global user.email "${EMAIL}" &> /dev/null
    git config --global user.name "${USER}" &> /dev/null
    rm -rf .git &> /dev/null
    git init &> /dev/null
    git add . &> /dev/null
    git commit -m m &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/QueenGoo/v7
    git push -f https://${TOKEN}@github.com/QueenGoo/v7.git &> /dev/null
    rm -rf /root/v7
    clear
    sleep 1
    echo "  Renew IP Address..."
    sleep 1
    echo "  Processing..."
    sleep 1
    echo "  Done!"
    sleep 1
    clear
TEXT2="
<code>───────────────────────────</code>
<code>    SUCCES RENEW  IP VPS</code>
<code>───────────────────────────</code>
<code>USERNAME       : $name</code>
<code>IP Address     : $ipdel</code>
<code>Expired On     : $exp4</code>
<code>───────────────────────────</code>
"
    echo ""
    echo -e "${OR}┌───────────────────────────────┐$NC"
    echo -e "${OR}│${NC}${g}.::.${NC} DONE RENEW IP VPS ${NC}${g}.::. $NC"
    echo -e "${OR}└───────────────────────────────┘$NC"
    echo -e "${OR}> USERNAME   :${NC}${yell} $name"
    echo -e "${OR}> IP ADDRESS :${NC}${yell} $ipdel"
    echo -e "${OR}> EXPIRED ON :${NC}${yell} $exp4"
    echo -e " ${OR}────────────────────────────────$NC"
    echo -e ""
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT2&parse_mode=html" $URL >/dev/null
}

clear

echo -e " ${OR}  ┌───────────────────────────────┐$NC"
echo -e " ${OR}  │${NC}${g} .::.${NC} MENU RESSELER IP ${NC}${g}.::. $NC"
echo -e " ${OR}  └───────────────────────────────┘$NC"
echo -e " ${OR}  │$NC$r NAME RESSELER   :$NC $SELLER"
echo -e " ${OR}  │$NC$r STATUS RESSELER :$NC $AKTIF"
echo -e " ${OR}  ┌───────────────────────────────┐$NC"
echo -e " ${OR}  │${NC}${g} 1.$NC ${c}ADD IP RESSELER"$NC     
echo -e " ${OR}  │${NC}${g} 2.$NC ${c}DELETE IP RESSELER"$NC
echo -e " ${OR}  │${NC}${g} 3.$NC ${c}RENEW IP RESSELER"$NC
echo -e " ${OR}  │${NC}${g} 4.$NC ${c}BACK TO MENU"$NC
echo -e " ${OR}  └───────────────────────────────┘$NC"
echo ""
read -p " Select From Options : " menu
case $menu in
1 | 01)
clear
add-ip
;;
2 | 02)
clear
del-ip
;;
3 | 03)
clear
renew-ip
;;
4 | 04)
menu
;;
*)
exit
;;
esac